//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANYUKT.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SANYUKT.Resource.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_ERROR.
        /// </summary>
        public static string CODE_0 {
            get {
                return ResourceManager.GetString("CODE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER_ERROR.
        /// </summary>
        public static string CODE_100 {
            get {
                return ResourceManager.GetString("CODE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string CODE_101 {
            get {
                return ResourceManager.GetString("CODE_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string CODE_102 {
            get {
                return ResourceManager.GetString("CODE_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failure.
        /// </summary>
        public static string CODE_103 {
            get {
                return ResourceManager.GetString("CODE_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not allowed to access this Application.
        /// </summary>
        public static string CODE_104 {
            get {
                return ResourceManager.GetString("CODE_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authrization Failure.
        /// </summary>
        public static string CODE_105 {
            get {
                return ResourceManager.GetString("CODE_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Token.
        /// </summary>
        public static string CODE_106 {
            get {
                return ResourceManager.GetString("CODE_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string CODE_107 {
            get {
                return ResourceManager.GetString("CODE_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PARAMETERS.
        /// </summary>
        public static string CODE_108 {
            get {
                return ResourceManager.GetString("CODE_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSUFFICIENT_LIMIT.
        /// </summary>
        public static string CODE_109 {
            get {
                return ResourceManager.GetString("CODE_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_TRANSACTION_AMOUNT.
        /// </summary>
        public static string CODE_110 {
            get {
                return ResourceManager.GetString("CODE_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_SERVICE_MAPPING.
        /// </summary>
        public static string CODE_111 {
            get {
                return ResourceManager.GetString("CODE_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_RECORD_FOUND.
        /// </summary>
        public static string CODE_112 {
            get {
                return ResourceManager.GetString("CODE_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNEXPECTED_ERROR_FOUND.
        /// </summary>
        public static string CODE_113 {
            get {
                return ResourceManager.GetString("CODE_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD_REQUEST.
        /// </summary>
        public static string CODE_114 {
            get {
                return ResourceManager.GetString("CODE_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION_ERROR.
        /// </summary>
        public static string CODE_115 {
            get {
                return ResourceManager.GetString("CODE_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BADREQUEST_METHOD_ERROR.
        /// </summary>
        public static string CODE_116 {
            get {
                return ResourceManager.GetString("CODE_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METHOD_NOT_FOUND.
        /// </summary>
        public static string CODE_117 {
            get {
                return ResourceManager.GetString("CODE_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMPLE_PASSWORD.
        /// </summary>
        public static string CODE_118 {
            get {
                return ResourceManager.GetString("CODE_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Not Done Please try again.
        /// </summary>
        public static string CODE_119 {
            get {
                return ResourceManager.GetString("CODE_119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charge Structure not Define.
        /// </summary>
        public static string CODE_120 {
            get {
                return ResourceManager.GetString("CODE_120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Details Missing.
        /// </summary>
        public static string CODE_121 {
            get {
                return ResourceManager.GetString("CODE_121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Error.
        /// </summary>
        public static string CODE_122 {
            get {
                return ResourceManager.GetString("CODE_122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found.
        /// </summary>
        public static string CODE_123 {
            get {
                return ResourceManager.GetString("CODE_123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Account No not found.
        /// </summary>
        public static string CODE_124 {
            get {
                return ResourceManager.GetString("CODE_124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service IFSC code not found.
        /// </summary>
        public static string CODE_125 {
            get {
                return ResourceManager.GetString("CODE_125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Account Name not Found.
        /// </summary>
        public static string CODE_126 {
            get {
                return ResourceManager.GetString("CODE_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servcie account Mobile no not found.
        /// </summary>
        public static string CODE_127 {
            get {
                return ResourceManager.GetString("CODE_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary cant&apos;t be Added.
        /// </summary>
        public static string CODE_128 {
            get {
                return ResourceManager.GetString("CODE_128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Benficiary.
        /// </summary>
        public static string CODE_129 {
            get {
                return ResourceManager.GetString("CODE_129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Payment Mode.
        /// </summary>
        public static string CODE_130 {
            get {
                return ResourceManager.GetString("CODE_130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Amount.
        /// </summary>
        public static string CODE_131 {
            get {
                return ResourceManager.GetString("CODE_131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTGS Transaction Amount must be more than 200000.
        /// </summary>
        public static string CODE_132 {
            get {
                return ResourceManager.GetString("CODE_132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter.
        /// </summary>
        public static string CODE_133 {
            get {
                return ResourceManager.GetString("CODE_133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Name is Required.
        /// </summary>
        public static string CODE_134 {
            get {
                return ResourceManager.GetString("CODE_134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is Required.
        /// </summary>
        public static string CODE_135 {
            get {
                return ResourceManager.GetString("CODE_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is Required.
        /// </summary>
        public static string CODE_136 {
            get {
                return ResourceManager.GetString("CODE_136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Policy not Defined.
        /// </summary>
        public static string CODE_137 {
            get {
                return ResourceManager.GetString("CODE_137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Amount should be Less than allowed amount.
        /// </summary>
        public static string CODE_138 {
            get {
                return ResourceManager.GetString("CODE_138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should be greter than allowed amount.
        /// </summary>
        public static string CODE_139 {
            get {
                return ResourceManager.GetString("CODE_139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not allowed to access this Application.
        /// </summary>
        public static string CODE_140 {
            get {
                return ResourceManager.GetString("CODE_140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string CODE_141 {
            get {
                return ResourceManager.GetString("CODE_141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address not allowed.
        /// </summary>
        public static string CODE_142 {
            get {
                return ResourceManager.GetString("CODE_142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender Mobile no is Required.
        /// </summary>
        public static string CODE_143 {
            get {
                return ResourceManager.GetString("CODE_143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode is Required.
        /// </summary>
        public static string CODE_144 {
            get {
                return ResourceManager.GetString("CODE_144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Id is Required.
        /// </summary>
        public static string CODE_145 {
            get {
                return ResourceManager.GetString("CODE_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should be greater than 0.
        /// </summary>
        public static string CODE_146 {
            get {
                return ResourceManager.GetString("CODE_146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Ref no is Required.
        /// </summary>
        public static string CODE_147 {
            get {
                return ResourceManager.GetString("CODE_147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Name is Required.
        /// </summary>
        public static string CODE_148 {
            get {
                return ResourceManager.GetString("CODE_148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Mobile No  is Required.
        /// </summary>
        public static string CODE_149 {
            get {
                return ResourceManager.GetString("CODE_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Acc No  is Required.
        /// </summary>
        public static string CODE_150 {
            get {
                return ResourceManager.GetString("CODE_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary Bank name is Required.
        /// </summary>
        public static string CODE_151 {
            get {
                return ResourceManager.GetString("CODE_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benficiary IFSC Code Required.
        /// </summary>
        public static string CODE_152 {
            get {
                return ResourceManager.GetString("CODE_152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not found.
        /// </summary>
        public static string CODE_153 {
            get {
                return ResourceManager.GetString("CODE_153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string CODE_154 {
            get {
                return ResourceManager.GetString("CODE_154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is Required.
        /// </summary>
        public static string CODE_155 {
            get {
                return ResourceManager.GetString("CODE_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile no is Required.
        /// </summary>
        public static string CODE_156 {
            get {
                return ResourceManager.GetString("CODE_156", resourceCulture);
            }
        }
    }
}
