//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANYUKT.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SANYUKT.Resource.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_ERROR.
        /// </summary>
        public static string CODE_0 {
            get {
                return ResourceManager.GetString("CODE_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERVER_ERROR.
        /// </summary>
        public static string CODE_100 {
            get {
                return ResourceManager.GetString("CODE_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Password.
        /// </summary>
        public static string CODE_101 {
            get {
                return ResourceManager.GetString("CODE_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Error.
        /// </summary>
        public static string CODE_102 {
            get {
                return ResourceManager.GetString("CODE_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failure.
        /// </summary>
        public static string CODE_103 {
            get {
                return ResourceManager.GetString("CODE_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not allowed to access this Application.
        /// </summary>
        public static string CODE_104 {
            get {
                return ResourceManager.GetString("CODE_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authrization Failure.
        /// </summary>
        public static string CODE_105 {
            get {
                return ResourceManager.GetString("CODE_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid API Token.
        /// </summary>
        public static string CODE_106 {
            get {
                return ResourceManager.GetString("CODE_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username.
        /// </summary>
        public static string CODE_107 {
            get {
                return ResourceManager.GetString("CODE_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_PARAMETERS.
        /// </summary>
        public static string CODE_108 {
            get {
                return ResourceManager.GetString("CODE_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSUFFICIENT_LIMIT.
        /// </summary>
        public static string CODE_109 {
            get {
                return ResourceManager.GetString("CODE_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_TRANSACTION_AMOUNT.
        /// </summary>
        public static string CODE_110 {
            get {
                return ResourceManager.GetString("CODE_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_SERVICE_MAPPING.
        /// </summary>
        public static string CODE_111 {
            get {
                return ResourceManager.GetString("CODE_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO_RECORD_FOUND.
        /// </summary>
        public static string CODE_112 {
            get {
                return ResourceManager.GetString("CODE_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNEXPECTED_ERROR_FOUND.
        /// </summary>
        public static string CODE_113 {
            get {
                return ResourceManager.GetString("CODE_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BAD_REQUEST.
        /// </summary>
        public static string CODE_114 {
            get {
                return ResourceManager.GetString("CODE_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION_ERROR.
        /// </summary>
        public static string CODE_115 {
            get {
                return ResourceManager.GetString("CODE_115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BADREQUEST_METHOD_ERROR.
        /// </summary>
        public static string CODE_116 {
            get {
                return ResourceManager.GetString("CODE_116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METHOD_NOT_FOUND.
        /// </summary>
        public static string CODE_117 {
            get {
                return ResourceManager.GetString("CODE_117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIMPLE_PASSWORD.
        /// </summary>
        public static string CODE_118 {
            get {
                return ResourceManager.GetString("CODE_118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Not Done Please try again.
        /// </summary>
        public static string CODE_119 {
            get {
                return ResourceManager.GetString("CODE_119", resourceCulture);
            }
        }
    }
}
