

namespace SANYUKT.Datamodel.Shared
{
    public enum ErrorCodes
    {
        NO_ERROR = 0,
        SERVER_ERROR = 500,
        INCORRECT_PASSWORD = 3999,
        VALIDATION_ERROR = 4000,
        AUTHENTICATION_FAILURE = 4001,
        USER_NOT_ALLOWED_APPLCATION_ACCESS = 4002,
        AUTHORIZATION_FAILURE = 4003,
        INVALID_API_TOKEN = 4004,
        PANCARD_IS_NOT_UNIQUE = 4005,
        AADHAR_CARD_IS_NOT_UNIQUE = 4006,
        PRIMARY_MOBILE_NO_IS_NOT_UNIQUE = 4007,
        SECONDARY_MOBILE_NO_IS_NOT_UNIQUE = 4008,
        PRIMARY_EMAIL_IS_NOT_UNIQUE = 4009,
        SECONDARY_EMAIL_IS_NOT_UNIQUE = 4010,
        SIMPLE_PASSWORD = 4011,
        INVALID_REQUEST = 4012,
        INVALID_DOCUMENT_FILE_FORMAT = 6001,
        EXCESSIVE_DOCUMENT_SIZE = 6002,
        INVALID_AGGREGATOR_DETAIL = 10001,
        REQUEST_NOT_PROCESSED = 10002,
        INVALID_UserName = 40012,
        INVALID_USER_DETAILS = 40014,
        INVALID_mobilenooremail = 40013,
        //OTP related
        INVALID_OTP_ERROR = 10050,
        OTP_MAX_ATTEMPTS_REACHED = 10051,
        OTP_EXPIRED = 10052,
        INVALID_PANCARD = 40015,

        //Sender Related
        SENDER_NOT_FOUND = 10100,
        INVALID_TRANSACTION_DETAIL = 10101,
        TP_END_SIDE_CONFIGURATION_ISSUE = 10102,
        TP_REQUIRED_PARAMETER_MISSING = 10103,
        TP_MAX_AMOUNT_EXCEEDED = 10104,
        TP_API_MANIPULATION_ISSUE = 10105,
        PMT_COMPLIANCE_ISSUE = 10106,
        ACTION_RETRY = 10107,
        //Receiver Related
        RECEIVER_NOT_FOUND = 10150,
        RECEIVER_CONTACT_DETAIL_NOT_FOUND = 10151,
        SENDER_CONTACT_DETAIL_NOT_FOUND = 10151,
        SENDER_ADDRESS_NOT_FOUND = 10152,
        SENDER_DOCUMENT_DETAIL_NOT_FOUND = 10153,
        INVALID_PARAMETERS = 20000,

        //Available Limit Detail
        INSUFFICIENT_LIMIT = 30001,

        //Transaction Error
        INVALID_TRANSACTION_AMOUNT = 40002,
        INVALID_SERVICE_MAPPING = 40003,
        PAYMENT_NOT_MATCH = 40005,
        //Export ToExcel Error
        NO_RECORD_FOUND = 50001,
        UNEXPECTED_ERROR_FOUND = 99999,

        //Document 
        MAX_DOCUMENT_UPLOAD_REACHED = 20001,
        PANCARD_NOT_VALID = 20002,
        AADHARCARD_NOT_VALID = 20003,
        DOCUMENT_NOT_UNIQUE = 20004,
        BC_Crtificate_NOT_VALID = 20005,
        Bank_Statement_NOT_VALID = 20006,
        DRA_Certificate_NOT_VALID = 20007,
        //Customer
        CUSTOMER_ALREADY_EXISTS = 101,
        CUSTOMER_BANK_ALREADY_EXISTS = 102,
        CUSTOMER_NOMINEE_ALREADY_EXISTS = 103,
        CUSTOMER_DOES_NOT_EXISTS = 104,
        CUSTOMER_PAN_EXISTS = 105,
        CUSTOMER_CAMS_KYC_EXISTS = 106,
        //Aadhaar related
        BAD_REQUEST = 400,

        //MMTC related
        APPLICATION_ERROR = 500,
        AUTHORIZATION_FAILED = 401,
        BADREQUEST_METHOD_ERROR = 400,
        METHOD_NOT_FOUND = 404
    }
}
